# Generated by Django 2.2.6 on 2019-10-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20191017_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
